### ISSUE TITLE
Comentários e agradecimento!

### ISSUE THREAD

**Issue by Nelson-Capello** [rodrigokiller/vscode-language-lsp#3]
Olá Rodrigo boa tarde, que legal, eu fiz alguma coisa parecida, mas eu não sei fazer os snippets, e também não sei empacotar e disponibilizar minha extensão no Marketplace, então, a sua ficou mais legal!

Obrigado por disponibilizar a iniciativa, eu gostaria de sugerir que vc alterasse o seu language-configuration.json incluíndo os símbolos de comentários da LSP, também de forma a ter o auto-complete, tipo, na minha configuração, quando vc digita @+espaço, automaticamente a @ de fechamento do comentário aparece, assim como para /* */, entretanto para comentários de bloco, meu auto-complete já formata como bloco. se não me engano vai estar no autoClosingPairs e no surroundingPairs.

Talvez queiras dar uma olhada como eu fiz, procure no meu perfil :)

Abraços!

**Comment by rodrigokiller** [comment]
Boa tarde @Nelson-Capello 
Desculpe a demora na resposta. 
Fico feliz que tenha gostado, espero que mais gente utilize também. 
Você quer me passar como ficou o seu, para eu implementar aqui? Ou de repente, se quiser, voce pode editar direto no arquivo que eu dou merge e faço o pull

Abraços

**Comment by Nelson-Capello** [comment]
oi Rodrigo bom dia! acho que demorei mais do que vc hahahaha

Eu quero aproveitar a oportunidade para estudar um pouco sobre o GitHub e suas funcionalidades, eu entendi que eu posso fazer um fork do seu projeto, editar no meu repositório e depois sugerir as modificações para o projeto-origem ou algo assim, eu vou tentar fazer dessa forma!

Então, não larguei mão de contribuir, agradeço a oportunidade!

**Comment by rodrigokiller** [comment]
Você fez corretíssimo. Deu tudo certinho com seu fork e "pull request". Fiz o "merge" também, e localmente fiz um comando para que o marketplace verificasse que há uma nova versão.
Agradeço imensamente a ajuda e fico à disposição.
Irei fechar esse "tópico".
